### PR TITLE
appoint a constitutional assembly

### PR DESCRIPTION
**Pull request by proofconstruction**
https://discourse.nixos.org/t/nixos-foundation-board-giving-power-to-the-community/44552#community-based-governance-2

This is a central location to make and discuss membership recommendations for the assembly, with the goal of transparency and openness similar to the RFC process.

### CODE REVIEW

**Comment by AshleyYakeley** [comment]
The list of assembly members is empty. Should this PR be a draft?

**Comment by infinisil** [comment]
Oh we didn't see that, we worked together with the board to propose this (already got the thumbs up by Ron): https://github.com/NixOS/foundation/pull/142

**Comment by fricklerhandwerk** [comment]
Eventually this will need a "hard" versioned document anyway, so we may pick it up later.

**Comment by infinisil** [comment]
Now done with https://discourse.nixos.org/t/nixos-foundation-board-constitutional-assembly-appointment/45504 :)

**Comment by refroni** [comment]
Closing as assembly is now in progress

**Pull request closed without merging**
